name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout Empty Project
      - name: Checkout Empty Project
        uses: actions/checkout@v2
        with:
          repository: litefeel/UnityEmptyProject

      # Set env
      - name: Set env UNITY_LICENSE
        run: my_var=$(cat UnityLicense/2019.2.11f1.ulf)
        run: echo "::set-env name=UNITY_LICENSE::{my_var}"
        run: echo "${{ env.UNITY_LICENSE }}"

      # Checkout This project
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          repository: litefeel/Unity-AlignTools
          path: Packages/MyPlugin
          ref: upm
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # # Test
      # - name: Run tests
      #   uses: webbertakken/unity-test-runner@v1.3
      #   with:
      #     unityVersion: 2019.2.11f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.2.11f1
          targetPlatform: WebGL 

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build